blog/urls.py
from django.urls import path,include

from . import views

app_name='blog'

urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('<int:id>',views.post_detail,name='post_detail'),
    path('tags/<slug:tag>',views.post_by_tag,name='post_by_tag'),
    path('category=<slug:category>',views.post_by_category,name='post_by_category'),


]

meals/urls.py
from django.urls import path,include

from . import views

app_name='meals'

urlpatterns = [
    path('', views.meal_list,name='meal_list'),
    path('<slug:slug>',views.meal_detail,name='meal_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    
    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('aboutus/',include('aboutus.urls',namespace='aboutus')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('home/',include('home.urls',namespace='home')),




    path('reservation/',include('reservation.urls',namespace='reservation')),

]

# urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header="Restuarant Admin Panel"
admin.site.site_title="Restuarant App Admin"
admin.site.site_index_title="Welcome To Restuarant Admin Panel"

meals/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Meals(models.Model):
    name=models.CharField(max_length=50)
    description=models.TextField(max_length=200)
    category=models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    people=models.IntegerField()
    price=models.DecimalField(max_digits=5,decimal_places=2)
    preparation_time=models.IntegerField()
    image=models.ImageField(upload_to='media')
    slug=models.SlugField(blank=True,null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug=slugify(self.name)
        super(Meals,self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='meal'
        verbose_name_plural='meals'

class Category(models.Model):
    category_name=models.CharField(max_length=50)

    def __str__(self):
        return self.category_name
    
    class Meta:
        verbose_name='category'
        verbose_name_plural='categories'

meals/views.py
from django.shortcuts import render

from .models import *
# Create your views here.
def meal_list(request):
    meal_list=Meals.objects.all()
    categories=Category.objects.all()
    context={
        'meal_list': meal_list,
        'categories':categories,
    }
    return render(request,'meals\meal_list.html',context)

def meal_detail(request,slug):
    meal_detail=Meals.objects.get(slug=slug)
    context={'meal_detail':meal_detail}
    return render(request,'meals\meal_detail.html',context)

meals/templates/meals/meal_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <div class="section">
        <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8" data-aos="fade-up">
                        <img class="meal_image" src="{{meal_detail.image.url}}" alt="" style="width: 100% !important;">
                        <h2>{{meal_detail}}</h2>
                        <p>{{meal_detail.description}}</p>
                        <p>For: {{meal_detail.people}} people</p>
                        <p>Preparation time: {{meal_detail.preparation_time}} minutes</p>
                        <p>Price: {{meal_detail.price}}$</p>
                    </div>  
                    

            </div>
        </div>
    </div> 

{% endblock body %}

meals/templates/meals/meal_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static\img\slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->
        
        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu List with Price</h2>

                <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                  
                  {% for category in categories %}
                    <li class="nav-item">
                      <a class="nav-link" id="{{category}}-tab" data-toggle="pill" href="#{{category}}" role="tab" aria-controls="{{category}}" aria-selected="true">{{category}}</a>
                    </li>
                  {% endfor %}

                </ul>

                <div class="tab-content" id="pills-tabContent">

                  {% for category in categories %}

                    <div class="tab-pane fade show" id="{{category}}" role="tabpanel" aria-labelledby="{{category}}-tab">
                      
                      {% for meal in meal_list %}

                        {% if meal.category == category %}
                          <div class="d-block d-md-flex menu-food-item">
                            <div class="text order-1 mb-3">
                              <h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal.name}}</a></h3>
                              <p>{{meal.description}}</p>
                            </div>
                            <div class="price order-2">
                              <strong>${{meal.price}}</strong>
                            </div>
                          </div> <!-- .menu-food-item -->
                        {% endif %}

                      {% endfor %}

                    </div>
                  {% endfor %}

                </div>


              </div>
            </div>
          </div>
        </div>


  

{% endblock body %}